service: class-services

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-1
  apiGateway:
    restApiId:
      Ref: ApiGatewayRestApi
    restApiRootResourceId:
      Fn::GetAtt:
        - ApiGatewayRestApi
        - RootResourceId
    cors:
      origins: "*"
      headers:
        - Content-Type
        - Authorization
        - X-Amz-Date
        - X-Api-Key
        - X-Amz-Security-Token
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowCredentials: false 

functions:
  class:
    handler: class.handler
    events:
      - http:
          path: /classes/{proxy+}
          method: any
          integration: lambda-proxy
      - http:
          path: /classes
          method: any
          integration: lambda-proxy
          

resources:
  Resources:
    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: shared-api-gateway
  Outputs:
    ApiGatewayRestApiId:
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: shared-api-gateway-id
    ApiGatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - ApiGatewayRestApi
          - RootResourceId
      Export:
        Name: shared-api-gateway-root-resource-id

plugins:
  - serverless-offline

# service: class-services

# provider:
#   name: aws
#   runtime: nodejs18.x
#   region: ap-southeast-1
#   apiGateway:
#     restApiId:
#       Fn::ImportValue: shared-api-gateway-id
#     restApiRootResourceId:
#       Fn::ImportValue: shared-api-gateway-root-resource-id

# functions:
#   grade:
#     handler: class.handler
#     # events:
#     #   - http:
#     #       path: grades/{proxy+}  # Chỉ định path là `grades/{proxy+}`
#     #       method: any
#     #       integration: lambda-proxy
#     #   - http:
#     #       path: /grades
#     #       method: any
#     #       integration: lambda-proxy
      

# resources:
#   Resources:
#     ApiGatewayResourceGrades:
#       Type: AWS::ApiGateway::Resource
#       Properties:
#         RestApiId:
#           Fn::ImportValue: shared-api-gateway-id
#         ParentId:
#           Fn::ImportValue: shared-api-gateway-root-resource-id
#         PathPart: grades  # Tạo resource `grades` dưới root resource